[theme]

# Primary accent for interactive elements
primaryColor = '#005005'

# Background color for the main content area
backgroundColor = '#212121'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#2e7d32'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"